/**
 /**
 * MAVI LINKING — CENTRALIZED PERMISSIONS & RBAC UTILITY
 * Defines all granular system permissions, system role defaults,
 * and permission delegation rules.
 */

const SYSTEM_PERMISSIONS = {
  // Student Management
  STUDENT_VIEW: 'STUDENT_VIEW',
  STUDENT_CREATE: 'STUDENT_CREATE',
  STUDENT_UPDATE: 'STUDENT_UPDATE',
  STUDENT_APPROVE: 'STUDENT_APPROVE',
  STUDENT_REJECT: 'STUDENT_REJECT',
  STUDENT_SUSPEND: 'STUDENT_SUSPEND',

  // Teacher Management
  TEACHER_VIEW: 'TEACHER_VIEW',
  TEACHER_CREATE: 'TEACHER_CREATE',
  TEACHER_UPDATE: 'TEACHER_UPDATE',

  // Recruiter Management
  RECRUITER_VIEW: 'RECRUITER_VIEW',
  RECRUITER_CREATE: 'RECRUITER_CREATE',
  RECRUITER_UPDATE: 'RECRUITER_UPDATE',

  // Department Management
  DEPARTMENT_VIEW: 'DEPARTMENT_VIEW',
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE: 'DEPARTMENT_UPDATE',

  // Placement & Training
  PLACEMENT_VIEW: 'PLACEMENT_VIEW',
  PLACEMENT_MANAGE: 'PLACEMENT_MANAGE',
  PLACEMENT_APPROVE: 'PLACEMENT_APPROVE',

  // Analytics & Reports
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  ANALYTICS_EXPORT: 'ANALYTICS_EXPORT',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Platform & Tenant Operations
  NOTIFICATION_MANAGE: 'NOTIFICATION_MANAGE',
  BILLING_VIEW: 'BILLING_VIEW',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',

  // Admin Management & Delegation
  ADMIN_CREATE: 'ADMIN_CREATE',
  ADMIN_UPDATE: 'ADMIN_UPDATE',
  ADMIN_SUSPEND: 'ADMIN_SUSPEND',
  PLATFORM_ADMIN_MANAGE: 'PLATFORM_ADMIN_MANAGE',
};

const ALL_PERMISSIONS = Object.values(SYSTEM_PERMISSIONS);

/**
 * Built-in Role Permission Defaults
 */
const SYSTEM_ROLE_PERMISSIONS = {
  super_admin: ALL_PERMISSIONS,
  platform_owner: ALL_PERMISSIONS,
  institution_admin: [
    SYSTEM_PERMISSIONS.STUDENT_VIEW,
    SYSTEM_PERMISSIONS.STUDENT_CREATE,
    SYSTEM_PERMISSIONS.STUDENT_UPDATE,
    SYSTEM_PERMISSIONS.STUDENT_APPROVE,
    SYSTEM_PERMISSIONS.STUDENT_REJECT,
    SYSTEM_PERMISSIONS.STUDENT_SUSPEND,
    SYSTEM_PERMISSIONS.TEACHER_VIEW,
    SYSTEM_PERMISSIONS.TEACHER_CREATE,
    SYSTEM_PERMISSIONS.TEACHER_UPDATE,
    SYSTEM_PERMISSIONS.RECRUITER_VIEW,
    SYSTEM_PERMISSIONS.DEPARTMENT_VIEW,
    SYSTEM_PERMISSIONS.DEPARTMENT_CREATE,
    SYSTEM_PERMISSIONS.DEPARTMENT_UPDATE,
    SYSTEM_PERMISSIONS.PLACEMENT_VIEW,
    SYSTEM_PERMISSIONS.PLACEMENT_MANAGE,
    SYSTEM_PERMISSIONS.PLACEMENT_APPROVE,
    SYSTEM_PERMISSIONS.ANALYTICS_VIEW,
    SYSTEM_PERMISSIONS.ANALYTICS_EXPORT,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_EXPORT,
    SYSTEM_PERMISSIONS.NOTIFICATION_MANAGE,
    SYSTEM_PERMISSIONS.BILLING_VIEW,
    SYSTEM_PERMISSIONS.AUDIT_LOG_VIEW,
    SYSTEM_PERMISSIONS.ADMIN_CREATE,
    SYSTEM_PERMISSIONS.ADMIN_UPDATE,
    SYSTEM_PERMISSIONS.ADMIN_SUSPEND,
  ],
  department_admin: [
    SYSTEM_PERMISSIONS.STUDENT_VIEW,
    SYSTEM_PERMISSIONS.STUDENT_UPDATE,
    SYSTEM_PERMISSIONS.STUDENT_APPROVE,
    SYSTEM_PERMISSIONS.STUDENT_REJECT,
    SYSTEM_PERMISSIONS.TEACHER_VIEW,
    SYSTEM_PERMISSIONS.DEPARTMENT_VIEW,
    SYSTEM_PERMISSIONS.PLACEMENT_VIEW,
    SYSTEM_PERMISSIONS.ANALYTICS_VIEW,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
  ],
  placement_admin: [
    SYSTEM_PERMISSIONS.STUDENT_VIEW,
    SYSTEM_PERMISSIONS.RECRUITER_VIEW,
    SYSTEM_PERMISSIONS.RECRUITER_CREATE,
    SYSTEM_PERMISSIONS.RECRUITER_UPDATE,
    SYSTEM_PERMISSIONS.PLACEMENT_VIEW,
    SYSTEM_PERMISSIONS.PLACEMENT_MANAGE,
    SYSTEM_PERMISSIONS.PLACEMENT_APPROVE,
    SYSTEM_PERMISSIONS.ANALYTICS_VIEW,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_EXPORT,
  ],
  academic_admin: [
    SYSTEM_PERMISSIONS.STUDENT_VIEW,
    SYSTEM_PERMISSIONS.STUDENT_UPDATE,
    SYSTEM_PERMISSIONS.TEACHER_VIEW,
    SYSTEM_PERMISSIONS.TEACHER_CREATE,
    SYSTEM_PERMISSIONS.TEACHER_UPDATE,
    SYSTEM_PERMISSIONS.DEPARTMENT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
  ],
  student_affairs_admin: [
    SYSTEM_PERMISSIONS.STUDENT_VIEW,
    SYSTEM_PERMISSIONS.STUDENT_CREATE,
    SYSTEM_PERMISSIONS.STUDENT_UPDATE,
    SYSTEM_PERMISSIONS.STUDENT_APPROVE,
    SYSTEM_PERMISSIONS.STUDENT_REJECT,
    SYSTEM_PERMISSIONS.NOTIFICATION_MANAGE,
  ],
  exam_admin: [
    SYSTEM_PERMISSIONS.STUDENT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_EXPORT,
  ],
  finance_admin: [
    SYSTEM_PERMISSIONS.BILLING_VIEW,
    SYSTEM_PERMISSIONS.AUDIT_LOG_VIEW,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_EXPORT,
  ],
  training_admin: [
    SYSTEM_PERMISSIONS.STUDENT_VIEW,
    SYSTEM_PERMISSIONS.PLACEMENT_VIEW,
    SYSTEM_PERMISSIONS.PLACEMENT_MANAGE,
  ],
};

/**
 * Check if an actor is authorized to delegate requested permissions.
 * Prevents privilege escalation (an admin cannot grant permissions they do not hold).
 */
function checkPermissionDelegation(actor, requestedPermissions = []) {
  if (!actor) return false;

  const actorRoles = actor.roles && actor.roles.length > 0 ? actor.roles : [actor.role];
  const isSuper =
    actorRoles.includes('super_admin') ||
    actorRoles.includes('platform_owner') ||
    actorRoles.includes('owner') ||
    actor.role === 'super_admin' ||
    actor.role === 'platform_owner' ||
    actor.role === 'owner';

  if (isSuper && (!actor.permissions || actor.permissions.length === 0)) return true;

  const actorPermissions = actor.permissions || [];
  const actorRoleDefaults = SYSTEM_ROLE_PERMISSIONS[actor.role] || [];
  const effectiveActorPermissions = new Set([...actorPermissions, ...actorRoleDefaults]);

  // Ensure every requested permission is possessed by the actor
  return requestedPermissions.every((perm) => effectiveActorPermissions.has(perm));
}

module.exports = {
  SYSTEM_PERMISSIONS,
  ALL_PERMISSIONS,
  SYSTEM_ROLE_PERMISSIONS,
  checkPermissionDelegation,
};
