const mongoose = require('mongoose');

const auditLogSchema = new mongoose.Schema(
  {
    actorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    actorRole: {
      type: String,
      default: 'system',
    },
    targetUserId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    institutionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Institution',
      default: null,
    },
    tenantId: {
      type: String,
      default: '',
    },
    departmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Department',
      default: null,
    },
    previousRole: {
      type: String,
      default: '',
    },
    newRole: {
      type: String,
      default: '',
    },
    action: {
      type: String,
      required: true,
      enum: [
        'STUDENT_PROFILE_UPDATED',
        'STUDENT_PRN_UPDATED',
        'STUDENT_ACADEMIC_INFO_UPDATED',
        'STUDENT_CONTACT_UPDATED',
        'STUDENT_PROFILE_PHOTO_UPDATED',
        'STUDENT_STATUS_UPDATED',
        'STUDENT_CREATED',
        'TEACHER_CREATED',
        'RECRUITER_CREATED',
        'DEPARTMENT_CREATED',
        'DEPARTMENT_UPDATED',
        'DEPARTMENT_TRANSFER',
        'DEPARTMENT_ADMIN_CREATED',
        'DEPARTMENT_ADMIN_APPOINTED',
        'DEPARTMENT_ADMIN_REASSIGNED',
        'DEPARTMENT_ADMIN_SUSPENDED',
        'DEPARTMENT_ADMIN_REACTIVATED',
        'DEPARTMENT_ADMIN_INVITED',
        'DEPARTMENT_ADMIN_ACTIVATED',
        'INSTITUTION_CREATED',
        'INSTITUTION_UPDATED',
        'INSTITUTION_SUSPENDED',
        'INSTITUTION_ADMIN_CREATED',
        'PLAN_CREATED',
        'PLAN_UPDATED',
        'PLAN_PUBLISHED',
        'PLAN_UNPUBLISHED',
        'PLAN_ARCHIVED',
        'PLAN_VERSION_CREATED',
        'PRICE_CHANGED',
        'INSTITUTION_PLAN_ASSIGNED',
        'SUBSCRIPTION_CREATED',
        'SUBSCRIPTION_CHECKOUT_INITIATED',
        'PAYMENT_SUCCESS',
        'PAYMENT_FAILED',
        'SUBSCRIPTION_SUSPENDED',
        'SUBSCRIPTION_CANCELLED',
        'EMAIL_CHANGE_REQUESTED',
        'EMAIL_CHANGE_VERIFICATION_SENT',
        'EMAIL_CHANGE_VERIFIED',
        'EMAIL_CHANGED',
        'EMAIL_CHANGE_FAILED',
        'EMAIL_CHANGE_EXPIRED',
        'EMAIL_CHANGE_RATE_LIMITED',
        'ADMIN_EMAIL_CHANGED',
        'ADMIN_INVITATION_SENT',
        'ADMIN_INVITATION_REVOKED',
        'ADMIN_ROLE_CHANGED',
        'ADMIN_SCOPE_CHANGED',
        'ADMIN_PERMISSIONS_CHANGED',
        'ADMIN_SUSPENDED',
        'ADMIN_REACTIVATED',
        'CUSTOM_ROLE_CREATED',
        'CUSTOM_ROLE_UPDATED',
        'CUSTOM_ROLE_DELETED',
        'STUDENT_REGISTRATION_CREATED',
        'EMAIL_VERIFICATION_SENT',
        'EMAIL_VERIFICATION_RESENT',
        'EMAIL_VERIFICATION_SUCCESS',
        'EMAIL_VERIFICATION_FAILED',
        'EMAIL_VERIFICATION_EXPIRED',
        'EMAIL_VERIFICATION_COMPLETED',
        'STUDENT_MOVED_TO_PENDING_APPROVAL',
        'STUDENT_APPROVAL_VIEWED',
        'STUDENT_ACCOUNT_APPROVED',
        'STUDENT_ACCOUNT_REJECTED',
        'STUDENT_ACCOUNT_SUSPENDED',
        'ACCOUNT_ACTIVATED',
        'VERIFICATION_REQUIRED_LOGIN_BLOCKED',
        'STUDENT_LOGIN_BLOCKED_EMAIL_UNVERIFIED',
        'STUDENT_LOGIN_BLOCKED_PENDING_APPROVAL',
        'INSTITUTION_CODE_VALIDATED',
        'INSTITUTION_CODE_CHANGED',
      ],
    },
    oldPRN: {
      type: String,
      default: null,
    },
    newPRN: {
      type: String,
      default: null,
    },
    changedFields: [
      {
        type: String,
      },
    ],
    details: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    result: {
      type: String,
      enum: ['SUCCESS', 'FAILURE', 'REJECTED'],
      default: 'SUCCESS',
    },
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

auditLogSchema.index({ targetUserId: 1, createdAt: -1 });
auditLogSchema.index({ institutionId: 1, createdAt: -1 });
auditLogSchema.index({ actorId: 1, createdAt: -1 });
auditLogSchema.index({ action: 1, createdAt: -1 });

module.exports = mongoose.model('AuditLog', auditLogSchema);
